### ISSUE TITLE
After clear-jobs, power-cycle fails for 7525

### ISSUE THREAD

**Issue by asyedham** [redhat-performance/badfish#150] opened 2020-12-04 04:52 UTC
**Your System Details**

* Python Version: Python 3.6.8
* Operating System: RHEL 7.7
* Target System Type: (_e.g. Dell, SuperMicro_) dell

**Describe the bug**

After using badfish to clear jobs on e20-h29-7525, when a run --power-cycle it gives the following error

```
(.venv) [root@e20-h31-7525 badfish]# python3 badfish.py -H mgmt-e20-h29-7525  -u quads -p  PASSWORD --power-state
- INFO     - Power state for mgmt-e20-h29-7525.example.com: On
(.venv) [root@e20-h31-7525 badfish]# python3 badfish.py -H mgmt-e20-h29-7525  -u quads -p  PASSWORD --clear-jobs --force
- INFO     - Job queue for iDRAC mgmt-e20-h29-7525** successfully cleared.
(.venv) [root@e20-h31-7525 badfish]# python3 badfish.py -H mgmt-e20-h29-7525**  -u quads -p  PASSWORD --power-cycle -v
- DEBUG    - Systems service: /redfish/v1/Systems/System.Embedded.1.
- DEBUG    - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
- DEBUG    - Getting allowable reset types.
- DEBUG    - Rebooting server: mgmt-e20-h29-7525**
- DEBUG    - url: https://mgmt-e20-h29-7525***/redfish/v1/Systems/System.Embedded.1
- DEBUG    - Current server power state is: On.
- ERROR    - Command failed to ForceOff server, status code is: 500.
- WARNING  - internal error, 
- DEBUG    - 
- ERROR    - There was something wrong executing Badfish
```
 
**To Reproduce / What were you Doing?**
 python3 badfish.py -H mgmt-{{ hostname}}  -u quads -p  password --clear-jobs --force
 python3 badfish.py -H mgmt-{{ hostname}}  -u quads -p  password --power-cycle

**Expected Behavior**
 python3 badfish.py -H mgmt-{{ hostname}}  -u quads -p  password --power-cycle
```
- DEBUG    - Systems service: /redfish/v1/Systems/System.Embedded.1.
- DEBUG    - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
- DEBUG    - Getting allowable reset types.
- DEBUG    - Rebooting server: mgmt-e20-h29-7525.example.com.
- DEBUG    - url: https://mgmt-e20-h29-7525.example.com/redfish/v1/Systems/System.Embedded.1
- DEBUG    - Current server power state is: On.
- INFO     - Command passed to ForceOff server, code return is 204.
- INFO     - Polling for host state: Not Down
- DEBUG    - url: https://mgmt-e20-h29-7525.example.com/redfish/v1/Systems/System.Embedded.1
- DEBUG    - Current server power state is: On.
- POLLING: [------------------->] 100% - Host state: On  
- INFO     - Command passed to On server, code return is 204.
```
This command should be executed successfully

Note: I have manually applied the changes from #149

**Comment by grafuls** [comment] 2022-06-14 13:23
Looks like the response from the redfish API returned an internal server error. This could potentially be remediated by running BF with `--racreset` before the power-cycle if anything but afraid that would be to costly in execution time plus you'd have to wait till idrac is back online.
I was not able to reproduce this with the same system `e20-h29-7525`.
```
$ badfish -H mgmt-e20-h29-7525 -u root -p password -t director -i ~/Sources/badfish-mine/config/idrac_interfaces.yml
- WARNING  - Job queue already cleared for iDRAC mgmt-e20-h29-7525, DELETE command will not execute.
- INFO     - Command passed to ForceOff server, code return is 204.
- INFO     - Polling for host state: Not Down
- POLLING: [------------------->] 100% - Host state: On  
- INFO     - Command passed to On server, code return is 204.
$ badfish -H mgmt-e20-h29-7525 -u root -p password --clear-jobs 
- INFO     - Job queue for iDRAC mgmt-e20-h29-7525 successfully cleared.
$ badfish -H mgmt-e20-h29-7525 -u root -p password --power-cycle
- INFO     - Command passed to ForceOff server, code return is 204.
- INFO     - Polling for host state: Not Down
- POLLING: [------------------->] 100% - Host state: On  
- INFO     - Command passed to On server, code return is 204
```
Please let us know if you are still experiencing this issue.

**Comment by grafuls** [comment] 2022-06-14 13:56
Just realized this might have been an issue that has already been resolved since it's been open for a while.
Closing this.

**Closed by grafuls** 2022-06-14 13:56 UTC
