### ISSUE TITLE
--reboot-only flag not working for 740xd

### ISSUE THREAD

**Issue by asyedham** [redhat-performance/badfish#118] opened 2020-08-04 09:15 UTC
When trying to reboot a target host (740xd in alias) I can see this error. But the same command worked for dell R630's
```
(.venv) [root@e23-h15-740xd badfish]#python3 badfish.py -H mgmt-e23-h21-740xd.alias  -u quads -p $password  --reboot-only
- ERROR    - Command failed to GracefulRestart server, status code is: 400.
- WARNING  - Unable to complete the operation because the value GracefulRestart entered for the property ResetType is not in the list of acceptable values.
- ERROR    - There was something wrong executing Badfish.
```

**Comment by QuantumPosix** [comment] 2020-08-04 11:31
This looks like the endpoint is missing from the latest versions of idrac9 compared to idrac8:
    "Actions": {
        "#ComputerSystem.Reset": {
            "ResetType@Redfish.AllowableValues": [
                "On",
                "ForceOff",
                "ForceRestart",
                "GracefulShutdown",
                "PushPowerButton",
                "Nmi"

Looking into this.

**Comment by grafuls** [comment] 2020-08-05 13:18
This is expected behavior on those 740s but we could work on having Badfish query for the available reset types.
As a work around you can use --power-cycle instead which calls the same function but with graceful=false.
Leaving this open for making the aforementioned improvements.

**Comment by grafuls** [comment] 2020-10-29 10:13
This has been resolved in https://github.com/redhat-performance/badfish/pull/141

**Closed by grafuls** 2020-10-29 10:13 UTC
Labels: Dell, bug
